#!/bin/bash

#define variables
block="mmcblk0"
prefix="$block""p"

#create entry point /update will be used to mount the "base" partition
upd_dir="/test"
echo "mkdir $upd_dir"
e=`mkdir $upd_dir`
datatar="$upd_dir/data.tar"
systemimg="$upd_dir/system.img"


curr_user_part="userdata "
new_user_part="userdatanew "

base_name_part="store "
base_num_part=""
user_num_part=""
n_sys_num_part="25"

boot_name=" boot "
boot_part=""

copy_data(){
	date1=$(date +"%s")
	###data
	
	# mount new partition
	#echo "mount -w -t ext4 /dev/block/$prefix$1 /data"
	#e=`mount -w -t ext4 /dev/block/$prefix$1 /data`
	# clean new partition
	

	###### I can't modify the file_contexts thus I can't create a security context for this folder
	echo "make_ext4fs -a /data /dev/block/$prefix$1"
	e=`make_ext4fs -a /data /dev/block/$prefix$1`
	###########

	echo "rm -rf /data/*"
	e=`rm -rf /data/*`
	
	echo "mount -w -t ext4 /dev/block/$prefix$1 /data"
	e=`mount -w -t ext4 /dev/block/$prefix$1 /data`

	# restore new partition
	echo "./twrpTar -x -d /data -t $datatar"
	e=`./twrpTar -x -d /data -t $datatar`
	#e=`umount /tmp_data`

	echo "restorecon -Rv /data"
	e=`restorecon -Rv /data`

	date2=$(date +"%s")
	diff=$(($date2-$date1))
	echo "Copy data ""$(($diff / 60)) minutes and $(($diff % 60)) seconds elapsed."
}

copy_system(){
	date1=$(date +"%s")
	###system
	# clean new partition
	echo "make_ext4fs -a /system /dev/block/$prefix$n_sys_num_part" 
	e=`make_ext4fs -a /system /dev/block/$prefix$n_sys_num_part`

	echo "umount /system" 
	e=`umount /system`

	#echo "mount -w -t ext4 /dev/block/$prefix$n_sys_num_part /system" 
	#e=`mount -w -t ext4 /dev/block/$prefix$n_sys_num_part /system`

	#echo "rm -rf /system/*" 
	#e=`rm -rf /system/*`

	# restore new partition
	#echo "cp -p -R $systemimg /system" 
	#e=`cp -p -R $systemimg /system`

	echo "cat $systemimg > /dev/block/$prefix$n_sys_num_part" 
	e=`cat $systemimg > /dev/block/$prefix$n_sys_num_part`

	#restore selinux context
	e=`restorecon -Rv /system`
	
	date2=$(date +"%s")
	diff=$(($date2-$date1))
	echo "Copy system ""$(($diff / 60)) minutes and $(($diff % 60)) seconds elapsed." 
}

IFS='
'
for f in `ls -la /dev/block/platform/msm_sdcc.1/by-name/`; 
	do
		case "$f" in 
    	*$curr_user_part*)
    		c_user_name_part=`basename $f`
			c_user_num_part=${c_user_name_part#$prefix}
			echo "Found $curr_user_part at partition $c_user_num_part" 
    	;;
    	*$new_user_part*)
    		n_user_name_part=`basename $f`
			n_user_num_part=${n_user_name_part#$prefix}
			echo "Found $new_user_part at partition $n_user_num_part" 
    	;;
    	*$base_name_part*)
    		n_base_name_part=`basename $f`
			n_base_num_part=${n_base_name_part#$prefix}
			echo "Found $base_name_part at partition $n_base_num_part" 
    	;;
    	*$boot_name*)
    		boot_part=`basename $f`
			n_boot_num_part=${boot_part#$prefix}
			echo "Found $boot_name at partition $n_boot_num_part" 
    	;;
	esac
done

echo "umount /data, /sdcard" 
e=`umount /data`
e=`umount /sdcard`

echo "mount -w -t ext4 /dev/block/$prefix$n_base_num_part $upd_dir"
e=`mount -w -t ext4 /dev/block/$prefix$n_base_num_part $upd_dir`

echo "copy system..."
copy_system
echo "done."

echo "mount /system"
if mount|grep "/system"; then
	echo "/system already mounted"
	e=`umount /system`
fi

echo "mount -w -t ext4 /dev/block/$prefix$n_sys_num_part /system" 
e=`mount -w -t ext4 /dev/block/$prefix$n_sys_num_part /system`

echo "copy_data $n_user_num_part"
copy_data $n_user_num_part

e=`umount /data`

echo "copy_data $c_user_num_part"
copy_data $c_user_num_part
 
e=`umount /data`
e=`umount $upd_dir`
e=`rm -rf $upd_dir`

exit 0

